### ISSUE TITLE
Bug in make_forecast.py

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#19]
the following exception is being raised:

```python
Traceback (most recent call last):
  File "make_forecast.py", line 488, in <module>
    df_val_hosp_cantons = make_predictions_all_cantons('hosp',  predictors, vaccine = True, smooth= True, hosp_as_predict = False,ini_date = '2020-03-01', title = None)
  File "make_forecast.py", line 275, in make_predictions_all_cantons
    x, y5,y50, y95,  target,train_size, forecast_dates, forecasts5, forecasts50,forecasts95 = rolling_predictions(target_name, df , hosp_as_predict,  ini_date = ini_date,split = 0.75,   horizon_forecast = horizon, maxlag=maxlag)
ValueError: not enough values to unpack (expected 10, got 6)
```

**Comment by fccoelho** [comment]
The exception is still happening @eduardocorrearaujo, even after you latest PR
