### ISSUE TITLE
Bug in the colombia script

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/EpiGraphHub#40]
After a while the script stops with the following exception:
```python
Traceback (most recent call last):
  File "colombia_data.py", line 87, in <module>
    load_into_db(client)
  File "colombia_data.py", line 72, in load_into_db
    for df_new in chunked_fetch(start, chunk_size, maxrecords):
  File "colombia_data.py", line 39, in chunked_fetch
    df_new.set_index(['id_', 'id_de_caso'] , inplace = True)
  File "/root/superset/lib/python3.7/site-packages/pandas/core/frame.py", line 4727, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id_de_caso'] are in the columns"
```

**Comment by eduardocorrearaujo** [comment]
I solved this problem in the last commit that I did.
